services:
  - type: web
    name: quality-education-portal
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OWNER_PASSKEY
        value: AdminEdu@2026
